apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rasa-bot
  labels:
    app: k8s-rasa-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-rasa-bot
  template:
    metadata:
      labels:
        app: k8s-rasa-bot
    spec:
      initContainers:
      - name: git-sync
        image: alpine/git
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /git 
          name: git-volume
        command:
        - git
        - clone
        - https://github.com/mastrogiovanni/rasa.git
        - /git
      - name: trainer-k8s-rasa-bot
        image: rasa/rasa_core:latest
        imagePullPolicy: IfNotPresent
        args: ['train', '--domain', '/mnt/model/domain.yml', '--stories', '/mnt/model/data/stories.md', '--out', '/mnt/trains'] 
        volumeMounts:
        - mountPath: /mnt/model
          name: git-volume
        - mountPath: /mnt/trains
          name: model
      - name: train-k8s-rasa-dialog
        image: rasa/rasa_nlu:latest-spacy
        imagePullPolicy: IfNotPresent
        args:
        - run
        - python
        - -m
        - rasa_nlu.train
        - -c
        - config.yml 
        - -d
        - /mnt/model/data/nlu.md
        - -o
        - /mnt/trains
        - --project
        - current
        volumeMounts:
        - mountPath: /mnt/model
          name: git-volume
      containers:
      - name: k8s-rasa-bot
        image: busybox
        imagePullPolicy: IfNotPresent 
        command:
        - sleep
        - "3600"
      volumes:
      - name: model
        emptyDir: {}
      - name: git-volume
        emptyDir: {}

