apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: action-server
  name: action-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: action-server
    spec:
      initContainers:
        - name: wait-training-begin
          image: busybox
          command: ["sh", "-c", "until test ! -f '/git/rasa/training-begin.out'; do sleep 2; done"]
          volumeMounts:
          - mountPath: /git
            name: git-volume
        - name: wait-training-end
          image: busybox
          command: ["sh", "-c", "until test -f '/git/rasa/training-terminated.out'; do sleep 2; done"]
          volumeMounts:
          - mountPath: /git
            name: git-volume
      containers:
      - image: rasa/rasa_core_sdk:latest
        name: action-server
        volumeMounts:
        - mountPath: /app/actions
          name: git-volume
          subPath: rasa/actions
      restartPolicy: Always
      volumes:
      - name: git-volume
        persistentVolumeClaim:
          claimName: rasa-pv-claim