apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rasa.fullname" . }}-nlu
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-nlu
    helm.sh/chart: {{ include "rasa.chart" . }}
    helm.sh/hook: "post-install"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rasa.name" . }}-nlu
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rasa.name" . }}-nlu
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-training
          image: busybox
          command: ["sh", "-c", "until test -f '/git/rasa/training-terminated.out'; do sleep 2; done"]
          volumeMounts:
          - mountPath: /git
            name: {{ include "rasa.name" . }}
      containers:
        - name: {{ .Chart.Name }}-nlu
          image: "{{ .Values.image.nlu.repository }}:{{ .Values.image.nlu.tag }}"
          imagePullPolicy: {{ .Values.image.nlu.pullPolicy }}
          args:
          - start
          - --path
          - models/rasa/models/rasa_nlu
#          ports:
#            - name: http
#              containerPort: 80
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
          - mountPath: /app/models
            name: {{ include "rasa.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ include "rasa.name" . }}
        persistentVolumeClaim:
          claimName: {{ include "rasa.fullname" . }}         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}



