apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-server # {{ include "rasa.fullname" . }}-action-server
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-action-server
    helm.sh/chart: {{ include "rasa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rasa.name" . }}-action-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rasa.name" . }}-action-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-training
          image: busybox
          command: ["sh", "-c", "until test -f '/git/rasa/training-terminated.out'; do sleep 2; done"]
          volumeMounts:
          - mountPath: /git
            name: {{ include "rasa.name" . }}
      containers:
      - image: "{{ .Values.image.action_server.repository }}:{{ .Values.image.action_server.tag }}"
        imagePullPolicy: {{ .Values.image.action_server.pullPolicy }}
        name: {{ .Chart.Name }}-action-server
        volumeMounts:
        - mountPath: /app/actions
          name: {{ include "rasa.name" . }}
          subPath: rasa/actions
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
      - name: {{ include "rasa.name" . }}
        persistentVolumeClaim:
          claimName: {{ include "rasa.fullname" . }}         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
