apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rasa.fullname" . }}-core
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-core
    helm.sh/chart: {{ include "rasa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rasa.name" . }}-core
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rasa.name" . }}-core
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-training
          image: busybox
          command: ["sh", "-c", "until test -f '/git/rasa/training-terminated.out'; do sleep 2; done"]
          volumeMounts:
          - mountPath: /git
            name: {{ include "rasa.name" . }}
      containers:
      - args:
        - start
        - --core
        - model/rasa/models/rasa_core
        - -c
        - rest
        - --endpoints
        - /app/model/rasa/config/endpoints.yml
        - -u
        - current/
        image: "{{ .Values.image.core.repository }}:{{ .Values.image.core.tag }}"
        imagePullPolicy: {{ .Values.image.core.pullPolicy }}
        name: {{ .Chart.Name }}-core
        ports:
        - containerPort: 5005
        volumeMounts:
        - mountPath: /app/model
          name: {{ include "rasa.name" . }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
      - name: {{ include "rasa.name" . }}
        persistentVolumeClaim:
          claimName: {{ include "rasa.fullname" . }}         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
