apiVersion: v1
kind: Service
metadata:
  name: action-server # {{ include "rasa.fullname" . }}-action-server
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-action-server
    helm.sh/chart: {{ include "rasa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: http-action-server
  selector:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-action-server
    app.kubernetes.io/instance: {{ .Release.Name }}

