apiVersion: v1
kind: Service
metadata:
  name: {{ include "rasa.fullname" . }}-core
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-core
    helm.sh/chart: {{ include "rasa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: http-core
  selector:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-core
    app.kubernetes.io/instance: {{ .Release.Name }}

