apiVersion: v1
kind: Service
metadata:
  name: {{ include "rasa.fullname" . }}-nlu
  labels:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-nlu
    helm.sh/chart: {{ include "rasa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http-nlu
  selector:
    app.kubernetes.io/name: {{ include "rasa.name" . }}-nlu
    app.kubernetes.io/instance: {{ .Release.Name }}

