apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ferrucciofacts.fullname" . }}
  labels:
    app: {{ template "ferrucciofacts.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ferrucciofacts.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ferrucciofacts.name" . }}
    spec:
      initContainers:
      - name: trainer-{{ template "ferrucciofacts.name" . }}
        image: rasa/rasa_core:latest
        command: ['train', '--domain', '/app/project/domain.yml', '--stories', '/app/project/data/stories.md', '--out', 'models'] 
        volumeMounts:
        - mountPath: /cache
          name: cache-volume



      containers:
      - name: {{ template "ferrucciofacts.name" . }}
        image: mastrogiovanni/ferrucciofacts-bot
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TELEGRAM_BOT_ID
            valueFrom:
              configMapKeyRef:
                name: {{ template "ferrucciofacts.fullname" . }}
                key: telegram_bot_id
      volumes:
      - name: model
        emptyDir: {}
      - name: git-volume
        gitRepo:
          repository: "https://github.com/mastrogiovanni/rasa"
